import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        manrope: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        bmono: ['var(--font-bmono)', 'monospace'],
        headline: ['Manrope'],
        body: ['Manrope'],
        label: ['Manrope'],
      },
      colors: {
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-container': 'var(--surface-container)',
        'surface-variant': 'var(--surface-variant)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-surface': 'var(--on-surface)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-error-container': 'var(--on-error-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'tertiary': 'var(--tertiary)',
        'secondary-container': 'var(--secondary-container)',
        'error': 'var(--error)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'outline-variant': 'var(--outline-variant)',
        'error-container': 'var(--error-container)',
        'surface-dim': 'var(--surface-dim)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'on-primary-container': 'var(--on-primary-container)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'background': 'var(--background)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-tertiary': 'var(--on-tertiary)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'primary': 'var(--primary)',
        'surface-tint': 'var(--surface-tint)',
        'on-secondary': 'var(--on-secondary)',
        'on-primary': 'var(--on-primary)',
        'tertiary-container': 'var(--tertiary-container)',
        'primary-container': 'var(--primary-container)',
        'surface-bright': 'var(--surface-bright)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-background': 'var(--on-background)',
        'surface': 'var(--surface)',
        'outline': 'var(--outline)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'secondary': 'var(--secondary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-error': 'var(--on-error)',
        'surface-container-high': 'var(--surface-container-high)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'primary-fixed': 'var(--primary-fixed)',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}

export default config